---
title: "TEST 5"
author: "suyni00i"
date: "2023-05-25"
output: html_document
---

### 0. Packages
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

## 1. Data Wrangling Problem
### 1.1 co2 를 불러오고 속성을 확인하시오.[10점]
```{r}
co2 <- read.csv("/Users/suyni00i/Documents/DAT/R Session/data/co2.csv")
head(co2)
str(co2)
```

## 1.2 다음과 같이 years 변수를 생성 후 str()을 통해서 확인하시오. [15 점]
```{r}
co2 <- co2 %>% 
  filter(Year >= 1960)

max(co2$Year)
```

```{r}
co2 <- co2 %>% 
  mutate(years = case_when(
  1960 <= Year & Year < 1970 ~ "1960s",
  1970 <= Year & Year < 1980 ~ "1970s",
  1980 <= Year & Year < 1990 ~ "1980s",
  1990 <= Year & Year < 2000 ~ "1990s",
  2000 <= Year & Year < 2010 ~ "2000s",
  2010 <= Year & Year < 2020 ~ "2010s",
  TRUE ~ "etc"
))

co2$years <- factor(co2$years, levels = c("1960s", "1970s", "1980s", "1990s", "2000s", "2010s"))

str(co2)
```

### 1.3 years별 총 co2 배출량이 많은 국가를 구하시오. [15점]
```{r}
co2 %>% 
  group_by(years, Country) %>% 
  summarise(emission = round(mean(Total))) %>% 
  arrange(years, -emission) %>% 
  group_by(years) %>% 
  top_n(3, emission)
```

### 1.4 다음과 같이 long format으로 변형하시오[10점]
```{r}
long_format <- pivot_longer(co2, cols = c(Solid.Fuel, Liquid.Fuel, Gas.Fuel, Cement, Gas.Flaring),
                            names_to = "factor",
                            values_to = "emission") %>% 
  mutate(factor = factor(factor, levels = c(
"Solid.Fuel", "Liquid.Fuel", "Gas.Fuel", "Cement", "Gas.Flaring"))) %>%
  arrange(factor)

head(long_format)
```

## Visualization Problem(Using ggplot2)
### 2.1 long format데이터를 이용해 다음과 같이 그리시오 [25점]
```{r}
long_format <- long_format %>% 
  group_by(years, factor) %>% 
  summarise(value = round(mean(emission)))

long_format
```

```{r}
ggplot(long_format) +
  facet_wrap(~ factor, scales = "free_y") +
  geom_line(aes(x = years, y = value, color = factor, group = factor)) +
  geom_point(aes(x = years, y = value, color = factor)) +
  scale_color_discrete() +
  theme(strip.background = element_rect(fill = "purple1"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none",
        text = element_text (family = "AppleGothic")) +
  labs(x = "년도별", y = "평균 배출량")
```

```{r}
# bocplot에서 자꾸 막힙니다......
co2 <- co2 %>% 
  filter(Country == c("CHINA (MAINLAND)", "INDIA", "JAPAN", "RUSSIAN FEDERATION", "UNITED KINGDOM", "UNITED STATES OF AMERICA")) %>% 
  group_by(Country, years) %>% 
  mutate(emission = round(mean(Total)))

ggplot(co2) +
  facet_wrap(~ Country, scales = "free", ncol = 2) +
  geom_boxplot(aes(x = years, y = emission, color = Country)) +
  theme(legend.position = "none")
```

