---
title: 'ggplot2: 8. Legends'
author: "suyni00i"
date: "2023-05-17"
output: html_document
---

```{r}
library(ggplot2)
library(gcookbook)
```

# Removing the Legend
```{r}
p <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) + geom_boxplot()
p
```

```{r}
p + guides(fill = FALSE)
p + scale_fill_discrete(guide = FALSE)
```
> guides(fill = FALSE)/scale_fill_discrete(guide = FALSE): remove legends
* if legends generated by color var.: guides(color = FALSE)/scale_color_discrete(guide = FALSE)

```{r}
p2 <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group, color = group)) +
  geom_boxplot()
p2
```

```{r}
p2 + guides(fill = FALSE)
p2 + guides(color = FALSE)
p2 + guides(fill = FALSE, color = FALSE)
```

# Changing the Position of a Legend
```{r}
p <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) + geom_boxplot() +
  scale_fill_brewer(palette = "Pastel2")
p + theme(legend.position = "top")
```

```{r}
# loc. of legend (outside)
p + theme(legend.position = "bottom")
p + theme(legend.position = "left")
p + theme(legend.position = "right")
```

```{r}
# loc. of legend(inside)
p + theme(legend.position = c(1, 0), legend.justification = c(0.5, 0.5))
p + theme(legend.position = c(0.5, 0.5), legend.justification = c(1, 0))
p + theme(legend.position = c(1, 1), legend.justification = c(1, 1))
```

```{r}
# border of legend(default = c(0.5, 0.5))
p + theme(legend.position = c(0.9, 0.2)) +
  theme(legend.background = element_rect(fill = "white", color = "black"))
```

```{r}
# transparentize border of legend/item
p + theme(legend.position = c(0.9, 0.2)) +
  theme(legend.background = element_blank()) + # remove overall border
  theme(legend.key = element_blank()) # remove border around each item
```

# Changing a Legend Title
```{r}
p <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) + geom_boxplot()
p
```

```{r}
# To change title of legend
p + labs(fill = "Condition")
# title of var.
p + scale_fill_discrete(name = "Condition")
# categorical var.
p + guides(fill = guide_legend(title = "Condition"))
```

```{r}
hw <- ggplot(heightweight, aes(x = ageYear, y = heightIn, color = sex)) + 
  geom_point(aes(size = weightLb)) + scale_size_continuous(range = c(1, 4))
hw
```

```{r}
# change name of color & size var.
hw + labs(color = "Male/Female", size = "Weight\n(pound)")
```

# Changing the Appearance of Legend Title
```{r}
p <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) + geom_boxplot()
p + theme(legend.title = element_text(face = "italic", family = "Times", color = "red", size = 18))
```

# Removing a Legend Title
```{r}
ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) + geom_boxplot() +
  guides(fill = guide_legend(title = NULL))
```

# Changing the Labels in a Legend
```{r}
p <- ggplot(PlantGrowth, aes(x = group, y = weight, fill = group)) +
  geom_boxplot()
p + scale_fill_discrete(labels = c("Control", "Treatment 1", "Treatment 2"))
```

```{r}
# change the order of labels in a legend
p + scale_fill_discrete(limits = c("trt1", "trt2", "ctrl"),
                        labels = c("Treatment 1", "Treatment 2", "Control"))
```

```{r}
p <- ggplot(heightweight, aes(x = ageYear, y = heightIn, shape = sex, color = sex)) +
  geom_point()
p
```

```{r}
p + scale_shape_discrete(labels = c("Female", "Male"))
p + scale_color_discrete(labels = c("Female", "Male"))
```

```{r}
p + scale_shape_discrete(labels = c("Female", "Male")) +
  scale_color_discrete(label = c("Female", "Male"))
```