---
title: "TEST 4"
author: "suyni00i"
date: "2023-05-24"
output: html_document
---

### 0. Packages
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

## 1. Data Wragling Problem
### 1.1 olympic.csv 를 불러오고 속성을 확인하시오.[10점]
```{r}
olympic <- read.csv("/Users/suyni00i/Documents/DAT/R Session/data/olympic.csv")

head(olympic)

str(olympic)
```

### 1.2 다음과 같이 데이터를 생성한 뒤 medals이라는 이름으로 저장하시오[10점]
```{r}
olympic <- olympic %>%
  separate(medal_type, into = c("medal", "none"), sep = " ", remove = FALSE) %>%
  select(-none) %>% 
  select(c(medal, athlete_name, athlete_sex, country_code, discipline))

head(olympic)
```

### 1.3 대한민국의 종목별 메달 개수를 구하시오 [15점]
```{r}
olympic_kor <- olympic[olympic$country_code == "KOR", ]

olympic_kor %>% 
  group_by(discipline, medal) %>%
  summarise(count = n()) %>%
  mutate(medal = factor(medal, levels = c("Gold", "Silver", "Bronze"))) %>% 
  arrange(medal, -count)
```

### 1.4 국가별 메달 획득 개수를 구하시오[20점]
```{r}
olympic_medals <- olympic %>% 
  group_by(country_code, medal) %>% 
  summarise(count = n())

order <- olympic_medals %>%
  group_by(country_code) %>%
  summarise(
    gold_count = sum(count[medal == "Gold"]),
    silver_count = sum(count[medal == "Silver"]),
    bronze_count = sum(count[medal == "Bronze"])
  ) %>%
  arrange(-gold_count, -silver_count, -bronze_count) %>%
  filter(gold_count > 0 | silver_count > 0 | bronze_count > 0) %>%
  pull(country_code)

olympic_medals <- olympic_medals %>%
   mutate(
    country_code = factor(country_code, levels = order),
    medal = factor(medal, levels = c("Gold", "Silver", "Bronze"))
  ) %>%
  arrange(country_code, medal)

olympic_medals
```

## 2. Visualization Problem(Using ggplot2)
### 2.1 국가별 전체 메달 개수를 barplot을 활용해 그리시오 [20점]
```{r}
top10 <- olympic_medals %>% 
  group_by(country_code) %>% 
  summarise(count = sum(count)) %>% 
  arrange(-count) %>% 
  head(10)

top10
```

```{r}
ggplot(top10) +
  geom_bar(aes(x = country_code, y = count, fill = country_code), stat = "identity") +
  labs(x = "국가", y = "메달 수", fill = "국가") +
  theme(text = element_text(family = "AppleGothic"))
```

### 2.2 국가별 메달 개수를 barplot을 활용해 그리시오 [25점]
```{r}
ggplot(olympic_medals %>% head(30)) +
  geom_bar(aes(x = country_code, y = count, fill = medal), stat = "identity", position = "dodge") +
  geom_text(aes(x = country_code, y = count, label = count, group = medal), position = position_dodge(width = 0.9), vjust = -0.5) +
  labs(x = "Country", y = "Number of Medal", fill = "Medal")

# NZL BRA의 금메달 개수가 같아서 그런지 BRA 대신 NZL이 뜹니다...
```

